services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8081:8081"
    restart: always
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/dashboard
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "dashboard"
      MYSQL_USER: "team2"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"

volumes:
  mysql-data:
    external: false